included:
  - MyName
excluded:
  - Pods

disabled_rules:
  - discarded_notification_center_observer
  - file_length
  - function_body_length
  - large_tuple
  - trailing_whitespace
  - colon
  - comma
  - force_cast

opt_in_rules:
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_first_not_nil
  - discouraged_object_literal
  - empty_count
  - empty_string
  - explicit_init
  - fallthrough
  - first_where
  - joined_default_parameter
  - literal_expression_end_indentation
  - modifier_order
  - multiline_arguments
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - prohibited_super_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - static_operator
  - toggle_bool
  - unused_import
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces

line_length: 200

identifier_name:
  min_length: 3
  excluded:
    - id
    - i
    - j
    - x
    - y
    - r
    - me
